#!/usr/bin/env bash

# Canonical runtime environment for G1Pilot.
#
# Usage:
#   source scripts/source_g1.sh sim
#   source scripts/source_g1.sh real <network-interface>
#
# Examples:
#   source scripts/source_g1.sh sim
#   source scripts/source_g1.sh real eno1
#
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  echo "This file must be sourced, not executed:"
  echo "  source $0 sim"
  echo "  source $0 real <network-interface>"
  exit 1
fi

_g1_source_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_g1_repo_root="$(cd "${_g1_source_dir}/.." && pwd)"

_g1_detect_ros_distro() {
  for distro in jazzy humble; do
    if [ -f "/opt/ros/${distro}/setup.bash" ]; then
      echo "${distro}"
      return
    fi
  done
  find /opt/ros -mindepth 2 -maxdepth 2 -name setup.bash 2>/dev/null \
    | sed -n 's#^/opt/ros/\([^/]*\)/setup.bash$#\1#p' \
    | sort \
    | tail -n 1
}

_g1_source_setup() {
  local setup_file="$1"
  local had_nounset=0
  case "$-" in
    *u*) had_nounset=1 ;;
  esac

  set +u
  # shellcheck disable=SC1090
  source "${setup_file}"

  if [ "${had_nounset}" -eq 1 ]; then
    set -u
  else
    set +u
  fi
}

_g1_prepend_path() {
  local var_name="$1"
  local path="$2"
  if [ ! -d "${path}" ]; then
    return
  fi

  local current_value="${!var_name:-}"
  case ":${current_value}:" in
    *":${path}:"*) ;;
    *) export "${var_name}=${path}${current_value:+:${current_value}}" ;;
  esac
}

_g1_python_minor() {
  /usr/bin/python3 - <<'PY'
import sys
print(f"{sys.version_info.major}.{sys.version_info.minor}")
PY
}

ROS_DISTRO="${ROS_DISTRO:-$(_g1_detect_ros_distro)}"
G1PILOT_WS="${G1PILOT_WS:-${HOME}/g1pilot_${ROS_DISTRO}_ws}"

_g1_arg1="${1:-${G1_PROFILE:-}}"
_g1_arg2="${2:-}"

case "${_g1_arg1}" in
  sim|sim_mujoco)
    G1_PROFILE=sim
    G1_INTERFACE="${_g1_arg2:-${G1_INTERFACE:-lo}}"
    _g1_default_ros_domain=1
    _g1_default_unitree_domain=1
    ;;
  real|real_g1)
    G1_PROFILE=real
    G1_INTERFACE="${_g1_arg2:-${G1_INTERFACE:-}}"
    _g1_default_ros_domain=0
    _g1_default_unitree_domain=0
    ;;
  "")
    echo "Usage: source ${BASH_SOURCE[0]} sim"
    echo "   or: source ${BASH_SOURCE[0]} real <network-interface>"
    return 1
    ;;
  *)
    echo "Unknown G1 profile: ${_g1_arg1}"
    echo "Usage: source ${BASH_SOURCE[0]} sim"
    echo "   or: source ${BASH_SOURCE[0]} real <network-interface>"
    return 1
    ;;
esac

if [ "${G1_PROFILE}" = "real" ] && [ -z "${G1_INTERFACE}" ]; then
  echo "Real G1 profile requires the robot network interface:"
  echo "  source ${BASH_SOURCE[0]} real <network-interface>"
  return 1
fi

if [ -z "${ROS_DISTRO}" ] || [ ! -f "/opt/ros/${ROS_DISTRO}/setup.bash" ]; then
  echo "ROS 2 ${ROS_DISTRO:-<unset>} was not found at /opt/ros/${ROS_DISTRO}/setup.bash."
  return 1
fi

# Source order matters:
#   1. ROS distribution underlay.
#   2. Per-user dependency workspace generated by setup_user_workspace.sh.
#   3. This checkout's install space as the final overlay, when built locally.
_g1_source_setup "/opt/ros/${ROS_DISTRO}/setup.bash"

if [ -f "${G1PILOT_WS}/deps/env_${ROS_DISTRO}_full.sh" ]; then
  _g1_source_setup "${G1PILOT_WS}/deps/env_${ROS_DISTRO}_full.sh"
elif [ -f "${G1PILOT_WS}/env_ros.sh" ]; then
  _g1_source_setup "${G1PILOT_WS}/env_ros.sh"
elif [ -f "${G1PILOT_WS}/.venv/bin/activate" ]; then
  _g1_source_setup "${G1PILOT_WS}/.venv/bin/activate"
fi

if [ -f "${_g1_repo_root}/install/setup.bash" ]; then
  _g1_source_setup "${_g1_repo_root}/install/setup.bash"
fi

rm -f "${G1PILOT_WS}/.venv/bin/register-python-argcomplete" 2>/dev/null || true

# ROS console scripts are generated with /usr/bin/python3. Activating the venv
# is not enough for those scripts, so export the venv and external Python
# package paths explicitly.
_g1_py_minor="$(_g1_python_minor)"
_g1_deps_prefix="${G1PILOT_DEPS_PREFIX:-${G1PILOT_WS}/deps/forest_ws/install}"

_g1_prepend_path PYTHONPATH "${_g1_deps_prefix}/lib/python${_g1_py_minor}/site-packages"
_g1_prepend_path PYTHONPATH "${_g1_deps_prefix}/local/lib/python${_g1_py_minor}/dist-packages"
_g1_prepend_path PYTHONPATH "${G1PILOT_WS}/.venv/lib/python${_g1_py_minor}/site-packages"
_g1_prepend_path PYTHONPATH "${G1PILOT_WS}/external/unitree_sdk2_python"
_g1_prepend_path PYTHONPATH "${G1PILOT_WS}/external/teleimager/src"

if [ "${G1_PROFILE}" = "sim" ]; then
  export G1_SIM_INTERFACE="${G1_INTERFACE}"
fi

export G1_PROFILE
export G1_INTERFACE
export G1_UNITREE_DOMAIN_ID="${G1_UNITREE_DOMAIN_ID:-${_g1_default_unitree_domain}}"
export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-${_g1_default_ros_domain}}"
export UNITREE_MUJOCO_DOMAIN_ID="${UNITREE_MUJOCO_DOMAIN_ID:-${G1_UNITREE_DOMAIN_ID}}"

# Unitree SDK2 Python uses CycloneDDS directly. Keep ROS 2 on FastDDS by
# default so ROS RMW and Unitree's SDK DDS are not competing inside the same
# Python process. Override only if you know the target runtime needs it:
#   export G1PILOT_ROS_RMW=rmw_cyclonedds_cpp
export RMW_IMPLEMENTATION="${G1PILOT_ROS_RMW:-rmw_fastrtps_cpp}"

# This CycloneDDS config is for Unitree SDK2 Python, not ROS when ROS is using
# FastDDS. It still matters for the Unitree channels.
export CYCLONEDDS_URI="<CycloneDDS><Domain><General><Interfaces><NetworkInterface name=\"${G1_INTERFACE}\" priority=\"default\" multicast=\"default\" /></Interfaces></General></Domain></CycloneDDS>"

if [ "${G1_INTERFACE}" = "lo" ]; then
  if command -v ip >/dev/null 2>&1 && ! ip link show lo | grep -q MULTICAST; then
    echo "Loopback multicast is disabled. Enable it with:"
    echo "  sudo ip link set lo multicast on"
  fi
fi

echo "ROS_DISTRO=${ROS_DISTRO}"
echo "G1_PROFILE=${G1_PROFILE}"
echo "G1PILOT_WS=${G1PILOT_WS}"
echo "G1PILOT_REPO=${_g1_repo_root}"
echo "G1_INTERFACE=${G1_INTERFACE}"
echo "G1_UNITREE_DOMAIN_ID=${G1_UNITREE_DOMAIN_ID}"
echo "ROS_DOMAIN_ID=${ROS_DOMAIN_ID}"
echo "RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}"

unset _g1_source_dir _g1_repo_root _g1_py_minor _g1_deps_prefix
unset _g1_arg1 _g1_arg2 _g1_default_ros_domain _g1_default_unitree_domain
unset -f _g1_detect_ros_distro _g1_source_setup _g1_prepend_path _g1_python_minor
